# Some properties will get overridden when running the docker compose file with the ENV variables
spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/order_booking_db
    username: <USERNAME>
    password: <PASSWORD>

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
  instance:
    prefer-ip-address: true